FROM python:3
#USER root

RUN apt-get update
RUN apt-get install ca-certificates

RUN apt-get -yqq install build-essential libssl-dev libffi-dev python3-pip python3-dev gnupg

RUN pip install --upgrade pip certifi
RUN pip install slack_bolt

ADD dummyfile /data/
RUN git clone https://github.com/pict3/slack_apps.git
WORKDIR slack_apps

